# Generated by Django 4.0.4 on 2022-04-28 03:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/', verbose_name='Фотография')),
                ('author', models.TextField(verbose_name='Автор')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок [uz]')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок [ru]')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок [en]')),
                ('description_uz', models.TextField(verbose_name='Описание [uz]')),
                ('description_ru', models.TextField(verbose_name='Описание [ru]')),
                ('description_en', models.TextField(verbose_name='Описание [en]')),
                ('content_uz', tinymce.models.HTMLField(verbose_name='Контент [uz]')),
                ('content_ru', tinymce.models.HTMLField(verbose_name='Контент [ru]')),
                ('content_en', tinymce.models.HTMLField(verbose_name='Контент [en]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннер'},
        ),
    ]
