# Generated by Django 4.0.4 on 2022-04-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contact_email_phone_alter_blog_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='email',
        ),
        migrations.AddField(
            model_name='phone',
            name='phone',
            field=models.CharField(default='default', max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
