# Generated by Django 4.0.4 on 2022-04-28 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_phone_email_phone_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Телефонные номера'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
