# Generated by Django 4.0.4 on 2022-04-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_phone_options_remove_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_uz', models.CharField(max_length=255, verbose_name='Адресс [uz]')),
                ('address_ru', models.CharField(max_length=255, verbose_name='Адресс [ru]')),
                ('address_en', models.CharField(max_length=255, verbose_name='Адресс [en]')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address_uz',
        ),
    ]
