# Generated by Django 4.0.4 on 2022-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_adress_remove_contact_address_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок [uz]')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок [ru]')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок [en]')),
                ('description_uz', models.TextField(verbose_name='Описание [uz]')),
                ('description_ru', models.TextField(verbose_name='Описание [ru]')),
                ('description_en', models.TextField(verbose_name='Описание [en]')),
                ('slogan_uz', models.CharField(max_length=255, verbose_name='Слоган [uz]')),
                ('slogan_ru', models.CharField(max_length=255, verbose_name='Слоган [uz]')),
                ('slogan_en', models.CharField(max_length=255, verbose_name='Слоган [uz]')),
                ('video', models.CharField(max_length=500, verbose_name='Ссылка на видео')),
                ('video_poster', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('background', models.ImageField(upload_to='images/', verbose_name='Задний фон шапки')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Achievments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=500, verbose_name='Количество')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок [uz]')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок [ru]')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок [en]')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
    ]
