# Generated by Django 4.0.4 on 2022-04-28 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_about_achievments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-publish',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique_for_date='publish'),
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Публикация')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='about',
            name='slogan_en',
            field=models.CharField(max_length=255, verbose_name='Слоган [en]'),
        ),
        migrations.AlterField(
            model_name='about',
            name='slogan_ru',
            field=models.CharField(max_length=255, verbose_name='Слоган [ru]'),
        ),
    ]
