# Generated by Django 4.0.4 on 2022-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_blog_options_blog_publish_blog_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fab fa-facebook-f', 'Facebook'), ('fab fa-google-plus-g', 'Google+'), ('fab fa-linkedin-in', 'LinkedIn'), ('fab fa-instagram', 'Instagram'), ('fab fa-twitter', 'Twitter'), ('fab fa-airplane', 'Telegram')], max_length=255, verbose_name='Соц-сеть')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Социальная сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
    ]
