# Generated by Django 4.0.4 on 2022-04-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_socials'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок сайта')),
                ('sitename', models.CharField(max_length=255, verbose_name='Название учереждения')),
                ('keywords', models.CharField(max_length=255, verbose_name='Ключевые слова [SEO]')),
                ('description', models.CharField(max_length=255, verbose_name='Описание сайта [SEO]')),
                ('worktime_uz', models.CharField(max_length=255, verbose_name='Рабочее время [uz]')),
                ('worktime_ru', models.CharField(max_length=255, verbose_name='Рабочее время [ru]')),
                ('worktime_en', models.CharField(max_length=255, verbose_name='Рабочее время [en]')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
            },
        ),
    ]
