# Generated by Django 4.0.4 on 2022-04-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_maindata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maindata',
            options={'verbose_name': 'Основное', 'verbose_name_plural': 'Основные'},
        ),
    ]
