# Generated by Django 4.0.4 on 2022-04-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_maindata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fas fa-trophy', 'Трофей'), ('fas fa-desktop', 'Монитор'), ('fas fa-book', 'Книжка')], max_length=255, verbose_name='Иконка')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Заголовок [uz]')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок [ru]')),
                ('title_en', models.CharField(max_length=255, verbose_name='Заголовок [en]')),
                ('description_uz', models.TextField(verbose_name='Описание [uz]')),
                ('description_ru', models.TextField(verbose_name='Описание [ru]')),
                ('description_en', models.TextField(verbose_name='Описание [en]')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
